# conda env create -f environment.yml to create the environment
# Requirement: git for the krakengui
name: neurokraken 

dependencies:
- python>=3.12
- anaconda
- pip
- pip:    
  - py5
  - opencv-python
  - pyserial
  - keyboard
  - psutil
  - rich
  - krakengui @ git+https://github.com/alexanderwallerus/kraken-gui@main
  - pyside6
  - matplotlib